#!/usr/bin/python
#
#  txt2CANTVMAC.py
#  Author: Sam Lin
#  Create: Sep 17, 2015
#
#  The MAC_*.bin file, which is generated by this program, is used for writing
#  MAC address into CANTV(CV638 & CV828).
#
#  The format of *.txt file must like this.
#  ========================
#  XX:XX:XX:XX:XX:XX
#  XX:XX:XX:XX:XX:XX
#  ......
#  ========================
#  That is one MAC address per line.


import sys
import os
import struct
import shutil

BIN_FILE_DIR_NAME = "MAC"

def str2bin(mac_address):
  if len(mac_address) == 12:
    pass
  else:
    raise ValueError('Incorrect MAC address format')

  fout = open(os.path.join(BIN_FILE_DIR_NAME,'MAC_'+mac_address.lower()+'.bin'),'wb+')
  output_data = b''

  for i in range(0,len(mac_address),2):
    data = struct.pack('B',int(mac_address[i:i + 2],16))
    output_data = output_data + data

  fout.write(output_data)
  fout.close()

def readMACAddr(txt_file):
  fin = open(txt_file,'rU')
  for line in fin:
    s = ''.join(line.strip().split(':'))
    str2bin(s)
  fin.close()  

def main():
  if len(sys.argv) != 2:
    print 'usage: ./txt2CANTVMAC.py file or python txt2CANTVMAC.py file'
    sys.exit(1)

  # Remove directory whose name is "MAC".
  shutil.rmtree(BIN_FILE_DIR_NAME)
  # # Create the "MAC" directory
  os.mkdir(BIN_FILE_DIR_NAME)
  readMACAddr(sys.argv[1])

if __name__=='__main__':
  main()
